### ISSUE TITLE
MicroPython v0.3.0 and V0.2.0 not working an CY8CPROTO-062-4343W board

### ISSUE THREAD

**Issue by Antonia-place** [Infineon/micropython#55]
Hi.
I see the following contest, https://www.hackster.io/contests/connectthingswithcode, and, because I already have on my desk one of the required boards (CY8CPROTO-062-4343W), I tried to start the project using MicroPython.
But, after installing the MicroPython V0.3.0 (latest), I can not comunicate anumore with the board. Then I trayed V0.2.0, with the same behavior. After that, I installed the first release of MicroPython, V0.1.1. This version was installed with success (like the prevous ones) and I can comunicate with the board. I have output in console, but here I observed other issues (please see below, in OBS).

For instalation, I used instruction from here: https://www.hackster.io/Infineon_Team/micropython-on-psoc-fcf1d0 and from here: https://ifx-micropython.readthedocs.io/en/latest/psoc6/installation.html. For latest version, V0.3.0, I used both methods: CLI and flash hex file with CyProgrammer. Also, I used the programmer for the V0.1.1 and for V0.2.0.

Command CTRL+B working only for MicroPython V0.1.1; for the other verssions, nothing was observed in console. Only thing that is working on all verssion is connection between board and ArduinoLab via serial connection.

Board is working, because during all these experiments, I used ModusToolbox to install some applications (to verify if the board is working). 

It is possible to be the external flash memory bad? How can I verifi/erase that external flash memory?

The board used is this one: https://www.infineon.com/cms/en/product/evaluation-boards/cy8cproto-062-4343w/

OBS: 
1. I tested the sample Blinky on MicroPython V0.1.1 (from here: https://www.hackster.io/Infineon_Team/micropython-on-psoc-fcf1d0) and the time.sleep_ms(1000) not working; the blink is done at the maximum speed!
2. I tested also the example from here: https://community.infineon.com/t5/Blogs/MicroPython-on-PSoC/ba-p/394582; this time, function sleep(1.0) not working!

I attached some pictures with console putput from ArduinoLab and traces from Cypress Programmer, from the latest flkashing round :
![Issue with PSoC6 microPython v0 3 0](https://github.com/Infineon/micropython/assets/10450789/0d383cc2-d981-455c-b91c-443fdc7cfee4)
![Issue with PSoC6 microPython v0 2 0](https://github.com/Infineon/micropython/assets/10450789/e48f93be-99c8-426d-a8d8-7aa613de08d9)
![PSoC6 MicroPython v0 1 1 working](https://github.com/Infineon/micropython/assets/10450789/3d00a878-214b-4bd1-a24e-c5e86f78113e)
[Logs from latest flashing round.log](https://github.com/Infineon/micropython/files/11723403/Logs.from.latest.flashing.round.log)

I want to clarify what is the issue: my board or MicroPython, or is other problem.

Thank you for support,
Mihai Popa

**Comment by jaenrig-ifx** [comment]
Hi @Antonia-place,

First of all, please consider only the v0.3.0 and upcoming releases. We are adding significant changes in every release, and some bugs or unsupported features would be solved/covered from one release to another.
We are keeping track of what is enabled [here](https://ifx-micropython.readthedocs.io/en/latest/psoc6/feature_list.html). 

I am trying to reproduce the issue but it is working in my case, both Ubuntu 20.05 and Windows 10 enterprise 22H2, and Arduino Lab IDE 0.6.
Arduino Lab for MicroPython is also under development, so you can give it a try with some more stable IDEs like Thonny, and for simple checks of the serial communication, any Serial Terminal like Putty, HTerm, TeraTerm... Minicom in Linux.

Which OS are you using? Can you share the output log when you run the [installation ](https://ifx-micropython.readthedocs.io/en/latest/psoc6/installation.html#quick-start) commands `quick-start` or `device-setup`?

Regards,
Juan

**Comment by Antonia-place** [comment]
Hello jaenrig-ifx,

My opetating sistem used on my PC is Windows 11, 22H2.
I tried both methot to install MicroPython on PSoC6 board: using hex file (with CyProgrammer and installing from cmd, with the same result.
I attached logs from installing process and pictures from Thonny, after flashing.
Hex file used with CyProgrammes is from here: https://github.com/infineon/MicroPython/releases

[LOG issue on win11.txt](https://github.com/Infineon/micropython/files/11768489/LOG.issue.on.win11.txt)
[LOGs from CyProgrammer with hex file.txt](https://github.com/Infineon/micropython/files/11768490/LOGs.from.CyProgrammer.with.hex.file.txt)
![Operating system version](https://github.com/Infineon/micropython/assets/10450789/cbb56b74-8eff-4b51-acad-79199868aad6)
![Thonny_001](https://github.com/Infineon/micropython/assets/10450789/caa9cc09-34e8-4d17-abcb-6069d1e5d785)
![Thonny_002](https://github.com/Infineon/micropython/assets/10450789/065cb857-d1c4-4d51-b05a-7f180b79d28d)
![Using hex file 0 3 0](https://github.com/Infineon/micropython/assets/10450789/f3376726-479b-4a70-855a-a274a0b7912f)

Please analyze the attached files.

Thank you for support,
Mihai

**Comment by jaenrig-ifx** [comment]
Hi Mihai,

All logs show no error. The device seems to be properly flashed. 
Also, as you can see the in the Arduino IDE terminal, MicroPython firmware and 0.3.0 version is flashed into the device. 

So what is then the actual problem, you don´t get to see the command prompt?
![image](https://github.com/Infineon/micropython/assets/47138227/6fcf90fd-3eac-4d0e-85f7-006d53bbbb10)
And you cannot interact with the device in REPL mode?

Regarding the Arduino IDE, as said, it is under development. There is chance that is a problem of the IDE tool, not our firmware or flashing process and the PSoC6 device. We have to diagnose properly which part of the whole setup could be failing.

Of course, the board can be broken... in many different ways. But if everything works fine when working under ModusToolbox, a hardware damage or failure should not be the problem. Anyhow, if you suspect that is the case and you can try with a new one that would be ideal.

**Comment by Antonia-place** [comment]
Hello jaenrif-ifx,

Yes, the issue is this: I can nomunicate with the board after flash MicroPython (from both methods) and I do not have the command promt (tested with Thonny and Arduino LAB).
I can see only the programmer and com port created.

in Thonny, I have the output in ted (see picture from prevous my post) and in Arduino LAB, sometimes, i have only partial output ( see the picture from my previous post).

now, I tryed to comunicate with the board using a simple RS232 comunication tool (Termite 3.3).
Please, see the output: it look like stop mounting the file system; that why I suspect that my board could be defective.

I will try to buy another one.

Attached new files:
[termite-3.3.zip](https://github.com/Infineon/micropython/files/11769410/termite-3.3.zip)
![Output in Termite RS232](https://github.com/Infineon/micropython/assets/10450789/fa012604-0fcc-4c98-8222-fb0c34031d38)

OBS: I see that the MicroPython v0.3.0 is much larger that V0.1.1.(3,5MB vs 0,8MB). This last version is flashed in the external flasm memory attached to the PSoC6  CY8PROTO-062-4343W board? Because with initial release of MicroPython (V0.1.1), the REPL is working good with all tools (Arduino LAB, Thonny ).  Because I am not shure that all the project flashed with ModusToolbox uses the externam flash memory.

Thank you,
Mihai

**Comment by jaenrig-ifx** [comment]
Hi @Antonia-place,

The program is not stored in the external flash. 
I am further checking the log, and I see that VTarget is 1.788V. Not sure if that is ok... I think it should be 3.3V. Can you check the USB cable?

Not sure, if in a previous program, there has been some flash configuration affecting this. Could you try to erase the device and flash a basic program mtb-example-hello-world prior this installation?

**Comment by jaenrig-ifx** [comment]
I will check on Windows 11, but I doubt that is the case. 
The suggestion of flashing a simple application from the ModusToolbox, is more in case that helps resetting any conflicting bootloader or flash setup which is causing the issue with this program.

**Comment by Antonia-place** [comment]
I already done that several times today and in previous days with the same result.

I recirded a video with this try; please rename the attached files as following and then unzip them; the result will be a video.
Rename file name Part1.txt in Video file - converted.zip.001
Rename file name Part2.txt in Video file - converted.zip.002
Rename file name Part3.txt in Video file - converted.zip.003

[Part1.txt](https://github.com/Infineon/micropython/files/11770586/Part1.txt)
[Part2.txt](https://github.com/Infineon/micropython/files/11770588/Part2.txt)
[Part3.txt](https://github.com/Infineon/micropython/files/11770592/Part3.txt)

I am waiting for my new board and i hope that will work. I was verry happy when I see that the MicroPython is working on PSoC ICs.

Thank you,
Mihai

**Comment by Antonia-place** [comment]
The only think that you can try to reproduce this issue is this (because I don't remember if first time I flashed the hex file with CyProgrammer of I installed MicroPython usping "quick-start command"): on a new board to flash the hex file using CyProgrammer. Maybe, somehow, I bricked the board in some way that I can not understand.

I am waiting the new board and I will try to install using "quick-start command". Then I will tell the results (I hope that will be positive).

Thank you, 
Mihai

**Comment by Antonia-place** [comment]
Hi.
Today I received the new Psoc 6 board.
The result is the same; moreover, on this new board, I have nothing on Thonny console and on other simple RS232 console.
I used first the "quick-start command" install method and then I used the CyProgrammer.

Here is all logs and pictures:
![Arduino LAB console](https://github.com/Infineon/micropython/assets/10450789/25967a67-3f4a-488f-a29b-b90275d01a50)
[Cmd instalation log.txt](https://github.com/Infineon/micropython/files/11798525/Cmd.instalation.log.txt)
[Log from CyProgrammer.txt](https://github.com/Infineon/micropython/files/11798526/Log.from.CyProgrammer.txt)
![Thonny console](https://github.com/Infineon/micropython/assets/10450789/a240f846-352d-431b-9bbd-9b6c4f18613b)

I don't want to buy another board, because, from my point of view, this is not an board issue...
PS: I tested programming this new board on two PCs: one with WIN11 (used for the first board) and another, with WIN10, with the same results.
I tested this new board before flash Micropython and it is working perfectly.
I used also different USB cables, including the ones from PSoC kit, with the same result.

Please, try to investigate what could be wrong with the MicroPython port on this PSoC6 board.

Thank you,
Mihai

**Comment by jaenrig-ifx** [comment]
Hi @Antonia-place,

We have found out that issue only happens for new boards in factory state...
We are working on a quick-fix to flash initially a hello-world.hex for this board while we found out more about the root cause.
Meanwhile, given that you have the ModusToolbox installed: **Can you please flash before the mtb-exxample-hello-world from the MTB?
And then rerun the quick-start command.
That should work.**

Thanks for your patience and sorry for the inconvenience.

**Comment by Antonia-place** [comment]
Hi,
I flashed the HelloWorkd example onsecond board (that who come today) and after that I flashed MicroPython using the "quick-start command" install method and now the board is working; see the attached pictures from Thonny and Arduino LAB.
![Output in Arduino LAB OK](https://github.com/Infineon/micropython/assets/10450789/e60d3b2b-9e08-4541-ab0f-e8219fa3f4b3)
![Output in Thonny OK](https://github.com/Infineon/micropython/assets/10450789/8b18e47e-2cc1-4e0e-ad28-67edae0d75f9)
But, for the fisrt board, the issue is still present, even flash the helloWorld and thet MicroPython...
But the good news is this: i have at least one board workins, so I can try to do something with that.

PS: Output in console for the first board remain the same (*after flash HelloWorld with MTB and MicroPython with cmd):
_ÿ÷?×ÿÿÿ¿=Wg½{ÿÿœÿ{yýß'Ÿ¿üÛ16$[02][00][00][00]býSM[00][00][00][00][00][00][00]&D@d[16]6&[16]v&L›÷7n
–ú6e/&[0C]&[06]Dù÷[04]ò[02]øÿ§[02]âþS[19]þŸ[00]Èüÿ¯[00]!ÿ¿ÿ[00]Hýÿ7}[02]ESÿ{ÿ[00][00]$$H[04]&L&&[16]l&266d[00]
_WLAN MAC Address : 48:EB:62:CF:0B:24
WLAN Firmware    : wl0: Jul 18 2021 19:15:39 version 7.45.98.120 (56df937 CY) FWID 01-69db62cf
WLAN CLM         : API: 12.2 Data: 9.10.39 Compiler: 1.29.4 ClmImport: 1.36.3 Creation: 2021-07-18 19:03:20 
WHD VERSION      : v2.5.0 : v2.5.0 : GCC 10.3 : 2022-09-23 13:14:02 +0800
[1B][H[1B][2JMicroPython v0.3.0 on 2023-04-14; CY8CPROTO-062-4343W with PSoC62
Use Ctrl-D to exit, Ctrl-E for paste mode
LFS2 filesystem mounted at /_

Both boards are from 121-60537-01 Rev 08 series

Thank you, Mihai

**Comment by jaenrig-ifx** [comment]
@Antonia-place glad to hear 😃 

Already adding that workaround for new boards to the installation script -> https://github.com/Infineon/micropython/pull/59

It will be soon available in a new release expected to happen in the upcoming days.

Yes, that workaround is not meant to fix the issues will your old board. I am afraid that the hardware is damage, or that some bootloading or flash permanent configuration is conflicting with the flashing of the MicroPython firmware.
