### ISSUE TITLE
I am using the following code for I2C" i2c = I2C(0,scl='P6_0',sda='P6_1',freq=4000000)" I don't know why I got endup in error 

### ISSUE THREAD

**Issue by kpk31081998** [Infineon/micropython#92]
I am using the following code for I2C" i2c = I2C(0,scl='P6_0',sda='P6_1',freq=4000000)" I don't know why I got end up in error the following error "Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: I2C initialisation failed with return code 4020d01 !"

please help me to resolve this error

Thank you

**Comment by jaenrig-ifx** [comment]
Hi @kpk31081998,

I just tried and I think your freq is too high. Can you make it 400000 (one 0 less)? That works for me.

**Comment by IFX-Anusha** [comment]
Hi @kpk31081998 ,

The Maximum allowed frequency is 1Mbps(1^6). Any frequency below should work.

Regards,
Anusha

**Comment by kpk31081998** [comment]
Thank you so much for both of you yes it worked when I reduced the frequency now I can see device address as 68 seems its giving the address in decimal and I converted it into hexa and I am using "i2c.readfrom(0x44, 4)" command but I am getting "ValueError: cyhal_i2c_master_read failed with return code aa2004 !"  I am new to micro python and I am following  [https://ifx-micropython.readthedocs.io/en/latest/psoc6/quickref.html](this documentation) for  CY8CPROTO-062-4343W PSoC Board.If you help me to resolve this error and help me to get data from my I2C device that would be very helpful 
Thank you

**Comment by jaenrig-ifx** [comment]
Hi @kpk31081998,

Can you tell us more about your hardware setup? which i2c slave device(sensor?) are you using? how are you connecting it to the board? are you using pull-up resistors? 

Regards,
Juan

**Comment by jaenrig-ifx** [comment]
Documentation fixed in #93.

**Comment by kpk31081998** [comment]
> Hi @kpk31081998,
> 
> Can you tell us more about your hardware setup? which i2c slave device(sensor?) are you using? how are you connecting it to the board? are you using pull-up resistors?
> 
> Regards, Juan

Sorry for the late replay, I am using "Infineon CY8CPROTO-062-4343W" as master and SHT40 as a slave I am not using any pullup resistors  I don't know why the above solution of reducing frequency works sometimes and sometimes not. I am getting an error "ValueError: I2C initialization failed with return code 4020d01 !" If you can help me to read data from SHT that would be very helpful 
Thank you

**Comment by jaenrig-ifx** [comment]
Hi @kpk31081998,

The initialization should initialize properly from software side despite if you have the sensor connected or not. Are you by any chance reusing that pin for any other purpose? Can you describe more the "sometimes"? Is it random? Or under certain changes in your setup?
Maybe you can share the example code or a snippet of it.

**Comment by jaenrig-ifx** [comment]
Hi @kpk31081998,

This issue will be closed due to inactivity. It can be reopened if the support is still needed.
